[general.plugin_registry.plugins]
  spaveripy = "/home/sp3c/deode_project/deode_plugins/spaverifynew/"
[platform]
  deode_home = "set-by-the-system"
[suite_control]
  suite_definition = "SpaveripySuiteDefinition"
[scheduler.ecfvars]
  case_prefix = "HARPVERIF_" # Add this to the suite name to not collide with OD case runs.
  ecf_host = "ecflow-gen-sp3c-001" # Hardcode your ecflow server (needed after v0.12.0)
[submission]
  submit_types = ["background_vm", "background_hpc", "parallel", "gnu", "serial", "spaveripy_group"]

[submission.spaveripy_group]
  SCHOST = "hpc"                             # Refers to the submission group in troika
  tasks = ["ExpsTransfer", "LinkObs", "Regrid", "PlotRegrid",  "Verification", "Panels", "RefUpdate","VerifyRef"]
  WRAPPER = ""

[submission.spaveripy_group.BATCH]
  NAME = "#SBATCH --job-name=@TASK_NAME@"
  NODES = "#SBATCH --nodes=1"
  NTASKS = "#SBATCH --ntasks=1"
  WALLTIME = "#SBATCH --time=01:05:00"

[submission.spaveripy_group.ENV]
  VERIF_OBS = "IMERG_pcp"
  DUSER = "aut6432"
  VERIF_USER = "sp3c"
  PATH_REF_GRIBS="/ec/res4/scratch/aut6432/DE_Verification/GRIBS/GDT_iekm/" # Where to find gribs for the reference model
  REF_NAME="Global_DT" # Name of your Reference model
  ECFS_ARCHIVE_RELPATH_HARPOUTPUT="/deode/SPAVERIF/cases/" # Root to store the HARP results in permanent archive
  ECFS_ARCHIVE_RELPATH_DEODEOUTPUT="/deode/" #Normally /deode/ for generic users, /DE_NWP/deode/ for operational (aut6432)
  USE_OPERATIONAL_INDEXING="yes" # Wether to use the Operational indexing (use in combination with operational DUSER=aut6432)
  TOMLS_DIR="/ec/res4/hpcperm/sp3c/deode_project/deode_spatial_verif/tomls/"   # Where to store the toml files which configure the OD case & spatial verification suite.
  PLUGIN_DIR="/home/sp3c/deode_project/deode_plugins/spaverifynew/" #Location of the spatial verification plugin
  DW_DIR="/home/sp3c/deode_project/Deode-Workflow/"                 #Location of the DW.
  TOOL_DIR="/ec/res4/hpcperm/sp3c/deode_project/deode_spatial_verif/"     #Location of the Spatial verification software
  LAUNCHS_DIR="/ec/res4/hpcperm/sp3c/deode_project/deode_spatial_verif/standalones/"  # Where to store the scripts that launch some verification steps outside of the suites.


[submission.spaveripy_group.MODULES]
  ECFLOW = ["load", "ecflow"]
  PYTHON311 = ["load", "python3/3.11.8-01"]

[submission.task_exceptions.ExpsTransfer.BATCH]
  WALLTIME = "#SBATCH --time=03:00:00"
[submission.task_exceptions.LinkObs.BATCH]
  WALLTIME = "#SBATCH --time=03:00:00"
[submission.task_exceptions.Regrid.BATCH]
  WALLTIME = "#SBATCH --time=03:00:00"
[submission.task_exceptions.PlotRegrid.BATCH]
  WALLTIME = "#SBATCH --time=03:00:00"
[submission.task_exceptions.Verification.BATCH]
  WALLTIME = "#SBATCH --time=03:00:00"
[submission.task_exceptions.Panels.BATCH]
  WALLTIME = "#SBATCH --time=03:00:00"
[submission.task_exceptions.RefUpdate.BATCH]
  WALLTIME = "#SBATCH --time=03:00:00"
[submission.task_exceptions.VerifyRef.BATCH]
  WALLTIME = "#SBATCH --time=03:00:00"

